project:
  type: website
  output-dir: docs
  
website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: country.qmd
        text: Country Analysis
      - href: life_population.qmd
        text: Life Expectancy and Population
      - href: life_gdp.qmd
        text: Life Expectancy and GDP per Capita

format:
  html:
    theme: cosmocerulean
    css: styles.css
    toc: true


